-- 코드를 입력하세요
SELECT BK.AUTHOR_ID, A.AUTHOR_NAME, BK.CATEGORY, SUM(BS.SALES * BK.PRICE) AS TOTAL_SALES
FROM BOOK AS BK
    LEFT JOIN AUTHOR AS A
    ON BK.AUTHOR_ID = A.AUTHOR_ID
    LEFT JOIN BOOK_SALES AS BS
    ON BK.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BK.AUTHOR_ID, BK.CATEGORY
ORDER BY A.AUTHOR_ID, BK.CATEGORY DESC