-- CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서  

# 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순 정렬, 
# 자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순 정렬해주세요.

SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    ROUND(C.DAILY_FEE * (1 - (P.DISCOUNT_RATE) / 100) * 30) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON 
    C.CAR_TYPE = P.CAR_TYPE
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON 
    C.CAR_ID = H.CAR_ID 
    AND '2022-11-01' <= H.END_DATE 
    AND H.START_DATE <= '2022-11-30'
WHERE 
    P.DURATION_TYPE = '30일 이상'
    AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
    AND H.CAR_ID IS NULL  -- 해당 기간에 대여 기록이 없는 차량
    AND ROUND(C.DAILY_FEE * (1 - (P.DISCOUNT_RATE) / 100) * 30) BETWEEN 500000 AND 2000000
ORDER BY 
    FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
