-- 코드를 입력하세요
# USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 
# 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문
# 결과는 총거래금액을 기준으로 오름차순 정렬해주세요.

SELECT U.USER_ID, U.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER AS U
LEFT JOIN
    (
        SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
        FROM USED_GOODS_BOARD
        WHERE STATUS = 'DONE'
        GROUP BY WRITER_ID
    ) AS B
ON U.USER_ID = B.WRITER_ID
WHERE B.TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES