-- 코드를 작성해주세요
SELECT H.EMP_NO, H.EMP_NAME, TT.GRADE,
    CASE WHEN TT.GRADE = 'S' THEN H.SAL * 0.2
    WHEN TT.GRADE = 'A' THEN H.SAL * 0.15
    WHEN TT.GRADE = 'B' THEN H.SAL * 0.1
    WHEN TT.GRADE = 'C' THEN 0
    END AS BONUS
FROM HR_EMPLOYEES AS H
LEFT JOIN 
    (SELECT HE.EMP_NO, HE.EMP_NAME, 
    CASE WHEN ((HG.SCORE + HG2.SCORE) / 2) >= 96 THEN 'S'
    WHEN ((HG.SCORE + HG2.SCORE) / 2) >= 90 THEN 'A'
    WHEN ((HG.SCORE + HG2.SCORE) / 2) >= 80 THEN 'B'
    ELSE 'C'
    END AS GRADE
    FROM HR_EMPLOYEES AS HE
    LEFT JOIN HR_DEPARTMENT AS HD
    ON HE.DEPT_ID = HD.DEPT_ID
    LEFT JOIN HR_GRADE AS HG
    ON HE.EMP_NO = HG.EMP_NO
    LEFT JOIN (
        SELECT *
        FROM HR_GRADE
        WHERE HALF_YEAR = 2
    ) AS HG2
    ON HE.EMP_NO = HG2.EMP_NO
    WHERE HG.HALF_YEAR = 1) AS TT
ON H.EMP_NO = TT.EMP_NO