-- 코드를 입력하세요
# home/grep/src/BOARD_ID/FILE_ID FILE_NAME FILE_EXT
SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS B
LEFT JOIN
USED_GOODS_FILE AS F
ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT USED_GOODS_BOARD.VIEWS FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1)